galaxy_info:
  author: Wolfgang Kulhanek, Jim Rigsbee
  description: Role to set up Nexus Artifact Repository on an OpenShift (Kubernetes) Cluster
  company: Red Hat
  license: Apache
  min_ansible_version: 2.6
  galaxy_tags:
    - openshift
    - kubernetes
    - k8s
    - ansible-operator
    - nexus
    - repository
dependencies: []
